name: tasikcode_app_flutter
description: Mobile Apps for TasikCode Community

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_icons: ^1.1.0
  flutter_widget_from_html_core: ^0.5.0+6
  google_fonts: ^1.1.0
  url_launcher: ^5.7.2
  websafe_svg: ^1.1.4
  webview_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/